AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for Static Website Hosting

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-website-bucket"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: "URL of the S3 website"
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: WebsiteURL

  WebsiteBucketName:
    Description: "Name of the S3 bucket for the website"
    Value: !Ref WebsiteBucket
    Export:
      Name: WebsiteBucketName
