services:
  db:
    build:
      context: ./development/db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./development/data/postgres:/var/lib/postgresql/data