services:
  bank-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DB_URL: "jdbc:postgresql://db:5432/dev_db"
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"

  db:
    build:
      context: ./development/db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./development/data/postgres:/var/lib/postgresql/data