openapi: "3.0.3"
info:
  title: "CNSD Notes API"
  description: "A simple API to get and post notes"
  version: "1.0.0"

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          example: "1"
        userId:
          type: string
          example: "1"
        content:
          type: string
          example: "This is a sample note content."

paths:
  /notes:
    get:
      summary: "Retrieve all notes"
      operationId: "getNotes"
      responses:
        '200':
          description: "A successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetNotesFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

    post:
      summary: "Create a new note"
      operationId: "createNote"
      requestBody:
        description: "Note object to be created"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "1"
                content:
                  type: string
                  example: "Content of the new note"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostNoteFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

      responses:
        '201':
          description: "Note successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
