Resources:
  NotesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: openapi.yml

  GetNotesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Tracing: Active
      Role: arn:aws:iam::632184430572:role/LabRole
      CodeUri: get-notes/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        GetNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: GET

  PostNoteFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Tracing: Active
      Role: arn:aws:iam::632184430572:role/LabRole
      CodeUri: post-note/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        PostNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: POST
