AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CNSD - Sample SAM Template for CNSD

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    ReservedConcurrentExecutions: 1

Resources:
  NotesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "CNSD Notes API"
      StageName: prod
      OpenApiVersion: '3.0.3'
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: openapi.yml

  GetNotesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Role: arn:aws:iam::632184430572:role/LabRole
      CodeUri: get-notes/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        GetNotesApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: GET

  PostNoteFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Role: arn:aws:iam::632184430572:role/LabRole
      CodeUri: post-note/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        PostNoteApi:
          Type: Api
          Properties:
            RestApiId: !Ref NotesApi
            Path: /notes
            Method: POST

  ProcessNoteFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Role: arn:aws:iam::632184430572:role/LabRole
      CodeUri: process-note/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        ProcessNoteEvent:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:us-east-1:632184430572:table/notes/stream/2024-11-12T11:30:40.383
            StartingPosition: LATEST