name: Deploy via ssh

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the application'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Version
        id: set-version
        run: |
          VERSION=${{ github.event.inputs.version }}
          if [ -z "$VERSION" ]; then
            VERSION=${{ github.event.release.tag_name }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.SSH_NAME}}@${{secrets.SSH_HOST}} '
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }};
            docker rm -f ${{ vars.DOCKER_IMAGE_NAME }} || true;
            docker run -d -p 80:8080 --name ${{ vars.DOCKER_IMAGE_NAME }}\
            -e SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE}" \
            -e DB_URL="${DB_URL}" \
            -e DB_USERNAME="${DB_USERNAME}" \
            -e DB_PASSWORD="${DB_PASSWORD}" \
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.VERSION }};
          '