on:
  push:
    branches:
      - module/2/opdracht/2/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: git fetch --unshallow --tags

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Set up SAM
        uses: aws-actions/setup-sam@v2

      - name: Test
        run: test

      - name: Build
        run: make

      - name: Deploy
        run: deploy
