name: Deploy via ssh

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the application'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }};
            docker rm -f ${{ vars.DOCKER_IMAGE_NAME }} || true;
            docker run -d -p 80:8080 --name cnsd-bank-app \
            -e SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE}" \
            -e DB_URL="${DB_URL}" \
            -e DB_USERNAME="${DB_USERNAME}" \
            -e DB_PASSWORD="${DB_PASSWORD}" \
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.version }};
          '