name: Run tests

on:
  pull_request:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Maven
        uses: s4u/maven-settings-action@v2

      - name: Run tests
        run: mvn test

      - name: Run SonarQube Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_QUBE_PROJECT_KEY }} -Dsonar.host.url=${{ secrets.SONAR_QUBE_URL }} -Dsonar.login=${{ secrets.SONAR_QUBE_TOKEN }}
