name: Create Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: Run SonarQube Analysis
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_QUBE_PROJECT_KEY }} \
          -Dsonar.host.url=${{ secrets.SONAR_QUBE_URL }} \
          -Dsonar.login=${{ secrets.SONAR_QUBE_TOKEN }}
